import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Provider } from "@/components/Poviders";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto({ weight:'400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coursegen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className,'antialiased min-h-screen pt-16')}>
        <Provider>
        <Navbar/>
        {children}
        <Toaster/>
        </Provider></body>
    </html>
  );
}
